### ISSUE TITLE
Create Widgets Utils

### ISSUE THREAD

**Issue by WilliamCunhaCardoso** [Ephenodrom/Dart-Basic-Utils#19]
There are some Widgets utils that I would like to propose. I'll make a PR for it

**Comment by Ephenodrom** [comment]
Hello and thank you for the issue. Can please explan how your widget utila work? Consider that this package has to run on pure Dart and therefore is not allowed to rely on Flutter.

Regards

**Comment by WilliamCunhaCardoso** [comment]
Hello.

So unfortunately I believe my PR will not be useful as it aims give usability to Widgets.

They are extensions to simplify some shortcuts. For example:

Container().marginOnly(top: 16)

Container().visibility(true)

Container().flexible()

**Comment by WilliamCunhaCardoso** [comment]
This is the PR:

https://github.com/Ephenodrom/Dart-Basic-Utils/pull/20

If it is not okay, you can close it

**Comment by Ephenodrom** [comment]
Hello @WilliamCunhaCardoso 

I closed the PR due to the codechanges don't fit in this package. As I said this package should work without relying on Flutter, so you can use it in every kind of project, from Flutte APP to HTTP Rest Server.

Feel free to contribute other code, extend the existing classes or recommend this package to other Flutter/Dart developer.

Regards
