### ISSUE TITLE
Many statics should be const

### ISSUE THREAD

**Issue by awhitford** [Ephenodrom/Dart-Basic-Utils#25]
Consider the following code:
```dart
class DateUtils {
  static int daysOfWeek = 7;
}  
  
main() {
  print("Hello, World!");
  print("DateUtils.daysOfWeek: ${DateUtils.daysOfWeek}");
  DateUtils.daysOfWeek = 8;
  print("DateUtils.daysOfWeek: ${DateUtils.daysOfWeek}");
}
```

It should be _illegal_ to override the `DateUtils.daysOfWeek`.  If this was declared as a `const`, the code would fail to compile (as it should).

**Comment by Ephenodrom** [comment]
@awhitford Hello and thanks for the improvements. The DateUtils class was more like a challenge to write the date parsing within a few hours, due to a request on gitter to implement such a feature. So far I have not developed an app where this can be used, so I think there is still a lot of space for improvements.

Regards
